// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function SaveEnv(arg1) {
  return window['go']['main']['App']['SaveEnv'](arg1);
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}

export function StopBackend() {
  return window['go']['main']['App']['StopBackend']();
}
