// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnv():Promise<Record<string, string>>;

export function GetStatus():Promise<string>;

export function OpenBrowser():Promise<void>;

export function SaveEnv(arg1:Record<string, string>):Promise<string>;

export function StartBackend():Promise<string>;

export function StopBackend():Promise<string>;
